# Generated by Django 4.2.11 on 2024-04-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('airways_name', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
